apiVersion: v2
name: streamforge
description: Unified Cloud-Native Helm chart for StreamForge (Argo Rollouts Blue-Green + KEDA Event-Driven Worker) on Azure Kubernetes Service (AKS)
type: application
version: 2.0.0
appVersion: "2.0.0"
