# Environment: PRODUCTION
global:
  environment: production

services:
  backend:
    replicaCount: 2
    image:
      repository: 393698973321.dkr.ecr.ap-southeast-1.amazonaws.com/streamforge-backend
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::393698973321:role/streamforge-backend-irsa-production"
    configMap:
      AWS_S3_BUCKET_NAME: "streamforge-media-production-393698973321"
      AWS_SQS_QUEUE_URL: "https://sqs.ap-southeast-1.amazonaws.com/393698973321/streamforge-transcode-queue-production"

  frontend:
    replicaCount: 2
    image:
      repository: 393698973321.dkr.ecr.ap-southeast-1.amazonaws.com/streamforge-frontend

  transcode-worker:
    image:
      repository: 393698973321.dkr.ecr.ap-southeast-1.amazonaws.com/streamforge-worker
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::393698973321:role/streamforge-worker-irsa-production"
    configMap:
      AWS_S3_BUCKET_NAME: "streamforge-media-production-393698973321"
      AWS_SQS_QUEUE_URL: "https://sqs.ap-southeast-1.amazonaws.com/393698973321/streamforge-transcode-queue-production"
      AWS_SQS_QUEUE_NAME: "streamforge-transcode-queue-production"

keda:
  maxReplicas: 5
  triggers:
    sqs:
      queueURL: "https://sqs.ap-southeast-1.amazonaws.com/393698973321/streamforge-transcode-queue-production"
