apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamforge-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: streamforge
  source:
    repoURL: https://github.com/icurff/vod-cfg.git
    targetRevision: main
    path: helm/streamforge
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: streamforge-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
