apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streamforge-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: streamforge
  source:
    repoURL: https://github.com/icurff/de-main.git
    targetRevision: develop
    path: vod-cfg/helm/streamforge
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: streamforge-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
