{{- range $name, $svc := .Values.services }}
{{- if and $svc.ingress $svc.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-ingress
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-{{ $name }}
  {{- with $svc.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $svc.ingress.className }}
  ingressClassName: {{ $svc.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $svc.ingress.host | quote }}
      http:
        paths:
          - path: {{ $svc.ingress.path | default "/" }}
            pathType: {{ $svc.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $name }}-svc
                port:
                  number: {{ $svc.port }}
{{- end }}
{{- end }}
