{{- range $name, $svc := .Values.services }}
{{- if eq $svc.kind "Rollout" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-preview
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    role: preview
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}

