{{- range $name, $svc := .Values.services }}
{{- if $svc.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-{{ $name }}
type: Opaque
stringData:
  {{- range $key, $val := $svc.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
